Github workflow for trigerring the csm release
dell/common-github-actions pull request #103
Opened 2024-12-10 12:24 UTC by meggm

# Description
This PR includes the workflow for triggering the auto release of csm drivers and modules using repository dispatch event.

# Issues
List the issues impacted by this PR:

| Issue ID |
| -------- |
|          | 

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

2024-12-10 12:41 UTC, donatwork commented on .github/workflows/auto-release-csm-driver-module.yaml
> +        run: echo "dummy retag for Quay.io"
Have you investigated if you can avoid pulling from quay.io and tag directly? This may need some API call perhaps? This can speed up the release process across all images as only a tag needs to be set in quay.io and no download/upload is needed. Later on we could get stricter and specify the tag/digest as the source image.

2024-12-10 14:26 UTC, shaynafinocchiaro requested changes

2024-12-10 14:26 UTC, shaynafinocchiaro commented on .github/workflows/auto-release-csm-driver-module.yaml
> +name: Auto Release CSM Drivers and Modules
We should only need and require one script to handle the release of drivers and modules. We already have an existing script: https://github.com/dell/common-github-actions/blob/main/.github/workflows/csm-release-driver-module.yaml. Please modify this one to your needs

2024-12-10 14:26 UTC, shaynafinocchiaro commented on .github/workflows/trigger-auto-csm-release-workflow.yaml
> +name: Trigger Auto Release Workflow
Can this be changed to say `Trigger Release of CSM Drivers and Modules`

2024-12-10 14:26 UTC, shaynafinocchiaro commented on .github/workflows/trigger-auto-csm-release-workflow.yaml
> +    name: Trigger Auto Release
Can this be changed to say `Trigger Release of CSM Drivers and Modules`

2024-12-10 14:26 UTC, shaynafinocchiaro commented on .github/workflows/trigger-auto-csm-release-workflow.yaml
> +            "dell/csm-replication",
Missing authorization, resiliency, and observability modules. Please uncomment powerflex and powerscale

2024-12-10 14:26 UTC, shaynafinocchiaro commented on .github/workflows/trigger-auto-csm-release-workflow.yaml
> +      - name: Trigger Auto Release
Can this be changed to say `Trigger Release of CSM Drivers and Modules`

2024-12-10 14:26 UTC, shaynafinocchiaro commented on .github/workflows/trigger-auto-csm-release-workflow.yaml
> +          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
add new line

2024-12-11 13:05 UTC, meggm commented on .github/workflows/trigger-auto-csm-release-workflow.yaml
> +            "dell/csm-replication",
Added the missing repos

2024-12-11 13:09 UTC, meggm commented on .github/workflows/auto-release-csm-driver-module.yaml
> +        run: echo "dummy retag for Quay.io"
@donatwork, Harish is working on this for step. He will be raising a different PR for Image Push step. I am commenting that part here

2024-12-11 13:47 UTC, shaynafinocchiaro requested changes

2024-12-11 13:47 UTC, shaynafinocchiaro commented on .github/workflows/csm-release-driver-module.yaml
> -  workflow_dispatch:
We should keep this. We'll still need to manually trigger this workflow for patch release and possibly major releases.

2024-12-11 13:47 UTC, shaynafinocchiaro commented on .github/workflows/csm-release-driver-module.yaml
> +      - name: Checkout repository
You're checking out the code in the `build-and-scan` already, is this still needed here?

2024-12-11 13:47 UTC, shaynafinocchiaro commented on .github/workflows/trigger-auto-csm-release-workflow.yaml
> +            "dell/karavi-observability"
Missing some metrics repos for observability - topology and powerflex.

2024-12-11 13:47 UTC, shaynafinocchiaro commented on .github/workflows/csm-release-driver-module.yaml
>  on:
You're trigger workflow is sending a repository dispatch event of type `auto-release-workflow`, that trigger needs to be added to this workflow

2024-12-11 13:47 UTC, shaynafinocchiaro commented
Please share how the trigger job has been tested

2024-12-11 14:00 UTC, shaynafinocchiaro commented on .github/workflows/csm-release-driver-module.yaml
>        version:
When this script is triggered, how will version be incremented?

2024-12-11 17:09 UTC, meggm commented on .github/workflows/csm-release-driver-module.yaml
> +      - name: Checkout repository
Yes, its needed

2024-12-11 17:10 UTC, meggm commented on .github/workflows/csm-release-driver-module.yaml
>        version:
version will be sent from the respective driver or modules repo. Updating in the Readme

2024-12-11 17:57 UTC, shaynafinocchiaro commented on README.md
> +    types: [auto-driver-module-release-workflow]
This doesn't match the event type in [trigger-auto-csm-release-workflow.yaml](https://github.com/dell/common-github-actions/pull/103/files#diff-7fcfe90e57f0dfb64a4e7a448315059a22a8048a5b64f92ae4a2ed4b859575e3)

2024-12-11 17:57 UTC, shaynafinocchiaro commented on README.md
> +For manual trigger from driver and module repositories, here is the example for the csi-powerscale repo:
Can you mention that this the manual workflow is recommended to be used for out of band releases such as patch releases or when the increment is a major version change.

2024-12-11 19:31 UTC, shaynafinocchiaro approved these changes

2024-12-12 06:28 UTC, harishp8889 approved these changes

2024-12-12 06:32 UTC, merged