Fix csi driver unit tests
dell/common-github-actions pull request #53
Opened 2021-11-20 07:31 UTC by jooseppi-luna

# Description
The objective of this PR is to enable the CSI teams to use the unit test action to run unit tests in our projects. We need to run the unit tests in a sub-directory to avoid having both the unit and integration tests. To accomplish this, I added a "test-folder" parameter into the action that is required and has the default value of `"."`. This follows the precedent set by other actions in this project and will allow the CSI teams to run unit tests without triggering integration tests as well.

One thing to note is that this may break tests for people already using this repo, since they will now have to provide three parameters instead of two.

# Issues
List the issues impacted by this PR:

| Issue ID |
| -------- |
|          | 

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [x] Ran against multiple CSI repositories to confirm that it works.

2021-11-23 14:04 UTC, medegw01 approved these changes

2021-11-23 19:05 UTC, tdawe commented on go-code-tester/action.yml
> +    required: true
Can this be set to false so that it doesn't break other repositories currently using this action?

2021-11-24 04:49 UTC, harishp8889 submitted a review, later dismissed

2021-11-24 11:31 UTC, shanmydell submitted a review, later dismissed

2021-11-24 12:46 UTC, gallacher requested changes
Requesting that @tdawe's, change be made.

2021-11-24 12:49 UTC, nb950 commented on go-code-tester/entrypoint.sh
> +TEST_OUTPUT=$(cd ${TEST_FOLDER} && go test -short -count=1 -race -cover ./... | tee /dev/stderr; exit ${PIPESTATUS[0]})
add -v to see verbose output in case of errors

2021-11-29 16:09 UTC, jooseppi-luna commented on go-code-tester/action.yml
> +    required: true
@tdawe the issue with leaving it false is that we would have two optional inputs that we would need to discriminate between, and I'm not sure how to do that. If this was a case where we could pass arguments from the command line, then it would be easy to set up some arguments to handle that, but since the script seems to expect them just to be passed sequentially with no flags or other discriminating arguments, the only easy fix I could figure out was to make the test-folder mandatory. I was debating whether I wanted to risk breaking some checks by making `skip-list` mandatory, but I looked into it and noticed that every single other action in this repo has some variation of this `test-folder` argument, and every one of them is mandatory, so based on that, I decided that it probably made sense to be consistent and make it mandatory here as well. Here are the examples I'm talking about:
https://github.com/dell/common-github-actions/blob/main/malware-scanner/action.yml#L12
https://github.com/dell/common-github-actions/blob/main/go-code-formatter-linter-vetter/action.yml#L12
https://github.com/dell/common-github-actions/blob/main/code-sanitizer/action.yml#L13

2021-11-29 16:11 UTC, jooseppi-luna commented on go-code-tester/action.yml
> +    required: true
If there is a way to accept multiple optional arguments and people think that is the best way to do it, then I'm happy to implement that instead.

2021-11-29 16:12 UTC, jooseppi-luna commented on go-code-tester/entrypoint.sh
> +TEST_OUTPUT=$(cd ${TEST_FOLDER} && go test -short -count=1 -race -cover ./... | tee /dev/stderr; exit ${PIPESTATUS[0]})
Good idea, I can do that

2021-11-29 18:06 UTC, nb950 commented on go-code-tester/action.yml
> +    required: true
refer :https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions , set optional =false with default value = "."
Optional A string representing the default value. The default value is used when an input parameter isn't specified in a workflow file.
wont this work ?

2021-11-29 18:49 UTC, jooseppi-luna commented on go-code-tester/action.yml
> +    required: true
@nb950 the issue with that is that, if I'm understanding this correctly, we still don't have a way to differentiate between optional arguments. If we make the test-folder argument optional, then what happens when someone doesn't provide a `test-folder` value but does provide a `skip-list` value? We'll have no way to tell the difference, and then the `skip-list` argument gets used as the `test-folder`, causing chaos.

2021-11-29 19:12 UTC, nb950 commented on go-code-tester/action.yml
> +    required: true
"what happens when someone doesn't provide a test-folder value"<-- default should be supplied is it not ?

2021-11-29 19:29 UTC, tdawe commented on go-code-tester/action.yml
> +    required: true
From the `dell/csm` repository I'm currently using this action as follows. I'm providing named parameters for `threshold` and `skip-list`.  If `test-folder` is optional, wouldn't the action see that I didn't provide it and assign it the value of `.` instead of confusing it with the `test-folder` value, since I explicitly provided that as a named parameter?
```
  test:
    name: Run Go unit tests and check package coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Run unit tests and check package coverage
        uses: dell/common-github-actions/go-code-tester@main
        with:
          threshold: 90
          skip-list: "github.com/dell/csm-deployment/handler"
```

2021-11-29 20:29 UTC, jooseppi-luna commented on go-code-tester/action.yml
> +    required: true
Ahh that is correct, I got confused by some earlier tests that I ran. I will make the parameter optional

2021-11-29 20:56 UTC, jooseppi-luna commented on go-code-tester/action.yml
> +    required: true
@tdawe @nb950 changes made

2021-11-29 21:04 UTC, jooseppi-luna commented
Changes requested by @nb950 @tdawe addressed

2021-11-29 23:44 UTC, nb950 approved these changes

2021-11-30 13:10 UTC, tdawe approved these changes

2021-11-30 13:38 UTC, gallacher requested changes
Let's wait until after the CSM 1.1 release before merging this.  I don't want any disruptions to our repositories this week.

2021-11-30 13:46 UTC, jooseppi-luna commented
@gallacher @tdawe sorry for the request to review just now, having internet issues and the lag caused me to mis-click. Thanks both for your reviews, we can merge this after the release.

2021-12-10 16:54 UTC, gallacher approved these changes

2021-12-10 16:55 UTC, merged